### ISSUE TITLE
"required" field is not defined for Field inferface

### ISSUE THREAD

**Issue by M1strall** [xogeny/siren-types#1]
In the FieldValueObject definition property "required : boolean" is missing
https://github.com/kevinswiber/siren/blob/master/siren.schema.json
```typescript
export interface FieldValueObject {
    value: string | number;
    title?: string;
    selected?: boolean;
}
```

**Comment by xogeny** [comment]
I don't understand your comment.  There is entry called `required` in `properties` for `FieldValueObject`.  Can you be more specific what you think the issue is?  What do you think the definite of the `FieldValueObject` interface should be? (it looks fine to me)

**Comment by mtiller** [comment]
Over two years and no response, so I'm closing this.  I suspect the `required` field was part of the JSON schema itself, not a property of Siren.
